application/MyShop/MyShop/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyShop.DAL;
using MyShop.Models;
using PagedList;

namespace MyShop.Controllers
{
    public class SaleController : ControllerBase
    {
        private ShopContext db = new ShopContext();

        // GET: Sale
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var products = db.products.OrderByDescending(p => p.ProductID);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        // GET: Sale/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Sale/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.productCategories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Sale/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,CategoryID,ProductDescription,Price,DiscountedPrice,SalesPeriodStartAt,SalesPeriodEndAt,StockQuantity")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.productCategories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Sale/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.productCategories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // POST: Sale/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,CategoryID,ProductDescription,Price,DiscountedPrice,SalesPeriodStartAt,SalesPeriodEndAt,StockQuantity")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.productCategories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Sale/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Sale/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

application/MyShop/MyShop/Views/Sale/Create.cshtml
@model MyShop.Models.Product

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Product Management", "Index", "Sale")</li>
                <li class="active">Create</li>
            </ol>
        </div>
    </div>
</div>
<div class="container">
    @using (Html.BeginForm())
    {

        <div class="row">
            <div class="col-xs-12">
                <div class="admin__products-wrapper">
                    <div class="admin__group">
                        <div class="admin__details">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <table class="table">
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.ProductName)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.CategoryID)</td>
                                    <td class="admin__value">
                                        @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.ProductDescription)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.Price)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.DiscountedPrice)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.DiscountedPrice, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DiscountedPrice, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodStartAt)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.SalesPeriodStartAt, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SalesPeriodStartAt, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodEndAt)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.SalesPeriodEndAt, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SalesPeriodEndAt, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                                <tr>
                                    <td class="admin__label">@Html.DisplayNameFor(model => model.StockQuantity)</td>
                                    <td class="admin__value">
                                        @Html.EditorFor(model => model.StockQuantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.StockQuantity, "", new { @class = "text-danger" })
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="admin__footer-button-wrapper">
                    <input class="btn btn-default btn-create" type="submit" value="Create"><a class="btn btn-default btn-back" href="@Url.Action("Index", "Sale")">Back to list</a>
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

application/MyShop/MyShop/Views/Sale/Delete.cshtml
@model MyShop.Models.Product

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Product Management", "Index", "Sale")</li>
                <li class="active">Delete</li>
            </ol>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1>Delete</h1><br>
            <h2>Are you sure want to delete this?</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="admin__products-wrapper">
                <div class="admin__group">
                    <div class="admin__details">
                        <table class="table">
                            <tr>
                                <td class="admin__label">Product Name</td>
                                <td class="admin__value">Product Name Here</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Category</td>
                                <td class="admin__value">Food</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Product Description</td>
                                <td class="admin__value">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga iste aut a eveniet nesciunt velit quaerat, officiis, quod placeat molestiae sit veritatis. Unde in ullam deserunt, incidunt repellendus veritatis. Quia.</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Price</td>
                                <td class="admin__value">$155.00</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Discounted Price</td>
                                <td class="admin__value">$100.00</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Sales Period Start At</td>
                                <td class="admin__value">2019-09-03 18:00:00</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Sales Period End At</td>
                                <td class="admin__value">2020-09-03 18:00:00</td>
                            </tr>
                            <tr>
                                <td class="admin__label">Stock Quantity</td>
                                <td class="admin__value">1000</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 text-center">
            <div class="admin__footer-button-wrapper">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                <input class="btn btn-default btn-delete" type="submit" value="Delete"><a class="btn btn-default btn-back" href="@Url.Action("Index", "Sale")">Back to list</a>
                }
            </div>
        </div>
    </div>
</div>

application/MyShop/MyShop/Views/Sale/Details.cshtml
@model MyShop.Models.Product

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Product Management", "Index", "Sale")</li>
                <li class="active">Details</li>
            </ol>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="admin__products-wrapper">
                <div class="admin__group">
                    <div class="admin__details">
                        <table class="table">
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.ProductName)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.ProductName)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.CategoryID)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.ProductCategories.CategoryName)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.ProductDescription)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.ProductDescription)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.Price)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.Price)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.DiscountedPrice)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.DiscountedPrice)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodStartAt)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.SalesPeriodStartAt)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodEndAt)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.SalesPeriodEndAt)
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.StockQuantity)</td>
                                <td class="admin__value">
                                    @Html.DisplayFor(model => model.StockQuantity)
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 text-center">
            <div class="admin__footer-button-wrapper"><a class="btn btn-default btn-back" href="@Url.Action("Edit", "Sale", new { id = Model.ProductID })">Edit</a><a class="btn btn-default btn-back" href="@Url.Action("Index", "Sale")">Back to list</a></div>
        </div>
    </div>
</div>

application/MyShop/MyShop/Views/Sale/Edit.cshtml
@model MyShop.Models.Product

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Product Management", "Index", "Sale")</li>
                <li class="active">Edit</li>
            </ol>
        </div>
    </div>
</div>
<div class="container">
    @using (Html.BeginForm())
    {
    <div class="row">
        <div class="col-xs-12">
            <div class="admin__products-wrapper">
                <div class="admin__group">
                    <div class="admin__details">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ProductID)
                        <table class="table">
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.ProductName)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.CategoryID)</td>
                                <td class="admin__value">
                                    @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.ProductDescription)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.Price)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.DiscountedPrice)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.DiscountedPrice, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiscountedPrice, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodStartAt)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.SalesPeriodStartAt, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SalesPeriodStartAt, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.SalesPeriodEndAt)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.SalesPeriodEndAt, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SalesPeriodEndAt, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td class="admin__label">@Html.DisplayNameFor(model => model.StockQuantity)</td>
                                <td class="admin__value">
                                    @Html.EditorFor(model => model.StockQuantity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.StockQuantity, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 text-center">
            <div class="admin__footer-button-wrapper">
                <input class="btn btn-default btn-save" type="submit" value="Save Changes"><a class="btn btn-default btn-back" href="@Url.Action("Index", "Sale")">Back to list</a>
            </div>
        </div>
    </div>
    }
</div>
    
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

application/MyShop/MyShop/Views/Sale/Index.cshtml
@model PagedList.IPagedList<MyShop.Models.Product>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li><a href="./">Home</a></li>
                <li class="active">Product Management</li>
            </ol>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="admin__products-wrapper">
                <div class="admin__group">
                    <div class="admin__heading">Product Management</div>
                </div>
                <div class="admin__group"><a class="btn btn-default btn-create" href="@Url.Action("Create", "Sale")">Create Product</a></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="admin__products-wrapper">
                <div class="admin__group">
                    @foreach (var item in Model)
                    {
                        <div class="admin__record">
                            <div class="admin__sub-group left">
                                <div class="admin__text"><b>@Html.DisplayFor(modelItem => item.ProductName)</b></div>
                                <div class="admin__text">Price: @Html.DisplayFor(modelItem => item.Price)</div>
                                <div class="admin__text">Stock: @Html.DisplayFor(modelItem => item.StockQuantity)</div>
                            </div>
                            <div class="admin__sub-group right">
                                <div class="admin__text text-right"><a class="btn-action" href="@Url.Action("Details", "Sale", new { id = item.ProductID })"><span class="glyphicon glyphicon-list"></span></a><a class="btn-action" href="@Url.Action("Edit", "Sale", new { id = item.ProductID })"><span class="glyphicon glyphicon-edit"></span></a><a class="btn-action" href="@Url.Action("Delete", "Sale", new { id = item.ProductID })"><span class="glyphicon glyphicon-trash"></span></a></div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="admin__pagination-wrapper">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                <div class="admin__group text-center">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        </div>
    </div>
</div>